### PR TITLE
Improve Wikidata QuickStatements

### PR DESCRIPTION
**Pull request by zuphilip**

### CODE REVIEW

**Comment by zuphilip** [comment]
@pigsonthewing Can you try this suggested version? It should fix the problems you reported.

**Comment by zuphilip** [comment]
Here is the direct link to the new suggested version: https://raw.githubusercontent.com/UB-Mannheim/zotkat/improve-wikidata/Wikidata%20QuickStatements.js

**Comment by pigsonthewing** [comment]
Not working for me at all now. I have even deleted, reinstalled, and restarted the browser. Other types of export still work.

**Comment by zuphilip** [comment]
What kind of "not working at all" are you experiencing? Can you still choose the WQS exporter manually? Do you see some kind of prohibition sign when trying to drag and drop? How about an item without a value in language?

**Comment by pigsonthewing** [comment]
I see a prohibition sign if I try to drag an item into QS, either choosing it manually or selecting by domain. Also "export library" fails with an unspecified error.

**Comment by zuphilip** [comment]
Can you try again with the new version (same link)? Otherwise maybe look at the error report under "Report Errors..." and copy the WQS related stuff here.

**Comment by pigsonthewing** [comment]
Thank you; working now. Fixes look good, except no values offered for P1476 (title).

**Comment by zuphilip** [comment]
Good. There is only a P1476 statement if you have also specified the language. Try to add the value for the language in Zotero, then you should see a P1476 statement.

Is there a way to add a P1476 statement without knowing the language?

**Comment by pigsonthewing** [comment]
> Is there a way to add a P1476 statement without knowing the language?

"und" is used for "language **und**etermined", and should be acceptable in such cases.

Alternatively, default to English (as done for the label!) or perhaps there is a user-setting for the user's preferred language?

**Comment by zuphilip** [comment]
I added the "und" in the latest commit. Thank you for the help!

**Pull request merged**
