### PR TITLE
[WQS]: Export with vertical bar instead of tab

### PR DESCRIPTION
**Pull request by nichtich**
This format is understood by QuickStatements 2 and easier to copy and paste.

### CODE REVIEW

**Comment by zuphilip** [comment]
Thank you! Looks good for me.

I will wait some days to see whether @pigsonthewing want to say something.

**Comment by pigsonthewing** [comment]
This format is not backwards compatible with QS1. QS2 is still described as "pre-alpha" , with a  cautionary note that 

> **The code is mostly untested and under heavy development. It might nuke Wikidata and steal your lunch. Try it on the Sandbox item (Wikidata Sandbox (Q4115189)) only, for now.**

https://www.wikidata.org/wiki/User:Magnus_Manske/quick_statements2

Maybe make it an option, or wait for QS2 to progress?

**Comment by nichtich** [comment]
QS2 looks more mature than QS1 and has better usability. Do you actually use QS1?

**Comment by pigsonthewing** [comment]
I've made some trial edits with QS2, but use QS1 regularly. As for "looks more mature ", I can only refer you again to the warning notice I quoted above.

**Pull request closed without merging**
